import type { PreviewThemeMode } from '../../../../../types';
import type { SmsColors } from './smsTypes';

export function getMobile13SmsContentColors(themeMode: PreviewThemeMode): SmsColors {
    return themeMode === 'dark'
        ? {
              shell: '#000000',
              header: '#000000',
              conversation: '#000000',
              receivedBubble: '#262628',
              sentBubble: '#32D15A',
              sentText: '#FFFFFF',
              primaryText: '#FFFFFF',
              secondaryText: '#8A8A8A',
              headerIcon: '#8A8A8A',
              headerActionIcon: '#8A8A8A',
              composer: '#1F1F1F',
              tealPoint: '#32D15A',
              link: '#8A8A8A',
              audioBackground: '#32D15A',
              audioIcon: '#FFFFFF',
              redPoint: '#FF3B30',
              menuIndicator: '#32D15A',
              statusCheck: '#FFFFFF',
              readReceiptBackground: '#32D15A',
              readReceiptForeground: '#FFFFFF',
              metadataIcon: '#8A8A8A',
              avatarBackground: '#5B586F',
              avatarForeground: '#FFFFFF',
              systemNavigationForeground: '#FFFFFF',
              quickReplyBorder: '#3A3A3C',
          }
        : {
              shell: '#FFFFFF',
              header: '#FFFFFF',
              conversation: '#FFFFFF',
              receivedBubble: '#E9E9E9',
              sentBubble: '#46D86B',
              sentText: '#FFFFFF',
              primaryText: '#000000',
              secondaryText: '#8A8A8A',
              headerIcon: '#8A8A8A',
              headerActionIcon: '#8A8A8A',
              composer: '#F8F8F8',
              tealPoint: '#46D86B',
              link: '#8A8A8A',
              audioBackground: '#46D86B',
              audioIcon: '#FFFFFF',
              redPoint: '#FF3B30',
              menuIndicator: '#46D86B',
              statusCheck: '#FFFFFF',
              readReceiptBackground: '#46D86B',
              readReceiptForeground: '#FFFFFF',
              metadataIcon: '#8A8A8A',
              avatarBackground: '#9DB1D5',
              avatarForeground: '#FFFFFF',
              systemNavigationForeground: '#000000',
              quickReplyBorder: '#E5E5E5',
          };
}
