/** Irregular pairs whose counterpart cannot be derived by a productive rule. */
export const exceptionPairs = [
    { masculine: 'actor', feminine: 'actriz' },
    { masculine: 'rey', feminine: 'reina' },
    { masculine: 'héroe', feminine: 'heroína' },
    { masculine: 'emperador', feminine: 'emperatriz' },
    { masculine: 'príncipe', feminine: 'princesa' },
    { masculine: 'hombre', feminine: 'mujer' },
    { masculine: 'padre', feminine: 'madre' },
    { masculine: 'papá', feminine: 'mamá' },
    { masculine: 'macho', feminine: 'hembra' },
    { masculine: 'yerno', feminine: 'nuera' },
    { masculine: 'caballo', feminine: 'yegua' },
    { masculine: 'toro', feminine: 'vaca' },
    { masculine: 'carnero', feminine: 'oveja' },
    { masculine: 'patriarca', feminine: 'matriarca' },
    { masculine: 'gallo', feminine: 'gallina' },
    { masculine: 'padrino', feminine: 'madrina' },
    { masculine: 'padrastro', feminine: 'madrastra' },
    { masculine: 'monje', feminine: 'monja' },
    { masculine: 'abad', feminine: 'abadesa' },
    { masculine: 'alcalde', feminine: 'alcaldesa' },
    { masculine: 'barón', feminine: 'baronesa' },
    { masculine: 'conde', feminine: 'condesa' },
    { masculine: 'duque', feminine: 'duquesa' },
    { masculine: 'jeque', feminine: 'jequesa' },
    { masculine: 'zar', feminine: 'zarina' },
] as const;

/**
 * Known objects, epicenes and common-gender nouns that collide with productive
 * endings. This small guard does not replace the caller's knowledge of meaning.
 */
export const blockedNouns = new Set([
    'dinero',
    'agujero',
    'sombrero',
    'florero',
    'llavero',
    'motor',
    'sector',
    'tractor',
    'factor',
    'vector',
    'reactor',
    'sensor',
    'neón',
    'padrón',
    'arnés',
    'revés',
    'interés',
    'cortés',
    'descortés',
    'volcán',
    'jardín',
    'botín',
    'cojín',
    'calcetín',
    'acordeón',
    'panteón',
    'balcón',
    'melón',
    'camión',
    'avión',
    'sillón',
    'jabón',
    'corazón',
    'sudor',
    'ardor',
    'color',
    'valor',
    'calor',
    'dolor',
    'tambor',
    'libro',
    'carro',
    'casa',
    'hora',
    'mesa',
    'ventana',
    'semana',
    'pingüino',
    'caso',
    'madero',
    'madera',
    'corona',
    'zona',
    'testigo',
    'modelo',
    'soldado',
    'persona',
    'víctima',
    'criatura',
    'lechuza',
    'ruiseñor',
    'gerenta',
    'atleta',
    'astronauta',
    'colega',
    'guía',
    'pediatra',
    'poeta',
    'profeta',
]);
